[WIP] Add donate modal
vergecurrency/vWallet pull request #36
Opened 2018-07-17 05:50 UTC by HDsign

<img width="1217" alt="schermafbeelding 2018-07-17 om 07 49 20" src="https://user-images.githubusercontent.com/3099122/42798893-14ffe04c-8996-11e8-94db-37226ff98fba.png">

2018-07-17 11:47 UTC, marpme requested changes

2018-07-17 11:47 UTC, marpme commented on src/components/modal/DonatePanel.tsx
> +import i18nReact from 'i18n-react'
Please use the new Tranlastion modules (`react-i18next`)

2018-07-17 11:47 UTC, marpme commented on src/components/modal/DonatePanel.tsx
> +  }
Do we really need the functions above?

2018-07-17 11:48 UTC, HDsign commented on src/components/modal/DonatePanel.tsx
> +  }
Dude it's a wippy 😛

2018-07-17 11:51 UTC, marpme requested changes

2018-07-17 11:51 UTC, marpme commented on src/components/modal/DonatePanel.tsx
> +        </p>
Those sentences should also be translated, let's wrap it for now and leave it english only. We will care about translations later on.

2018-07-17 11:51 UTC, marpme commented
MOAR DENY.

2018-07-17 11:57 UTC, HDsign commented
![schermafbeelding 2018-07-17 om 13 56 20](https://user-images.githubusercontent.com/3099122/42815922-34cf8c14-89c9-11e8-9055-6aa8d215e768.png)
@marpme haha it's a fucking WIP 😆 
You're reviewing the shit out of a WIP.
Go do you exams 😝

2018-07-17 12:12 UTC, marpme commented
I'm done, so fucking done. hahaha

2018-07-17 21:41 UTC, SwenVanZanten commented
<img width="1218" alt="schermafbeelding 2018-07-17 om 23 29 24" src="https://user-images.githubusercontent.com/3099122/42847015-e3e3f770-8a1a-11e8-97e9-26080cc72974.png">


I've added some components to reduce code duplication.
I've copied the `sendTransaction` method though.
In the future we should abstract that too.

2018-07-18 08:48 UTC, marpme commented
I would love to try to abstract that send Transaction method, do you think that this is possible with given structure?

2018-07-18 08:52 UTC, SwenVanZanten commented
Yes of course! 😃 I think you should create a class with you feed the amount and to address.
Then update the status with a listener and the ending status with a listener.
Or something like that.

2018-07-18 13:12 UTC, marpme commented
Promise: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

Well, we could use that, so that you can subscribe certain events.

2018-07-18 13:40 UTC, SwenVanZanten commented
👍 cool.
But do you want to do that in this branch?
Or make new branch after this is merged

2018-07-18 18:53 UTC, merged

2018-07-18 18:53 UTC, marpme commented
Merged gonna use a new branch and file a new issue for this